import 'pre-commit-with-uv.just' # overrides core.just
import 'uv.just' # overrides core.just
import 'core.just'
import 'pick/pick.just'
# Note: The imports above were generated by `just pick`


_default:
    just --list
