#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(dirname -- "${BASH_SOURCE[0]}")"

check_dependencies() {
    local missing_deps=()

    if ! command -v git &> /dev/null; then
        missing_deps+=("Git: https://git-scm.com/downloads")
    fi

    if ! command -v dialog &> /dev/null; then
        missing_deps+=("dialog: https://invisible-island.net/dialog/")
    fi

    if ! command -v jq &> /dev/null; then
        missing_deps+=("jq: https://jqlang.org/download/")
    fi

    if ! command -v just &> /dev/null; then
        missing_deps+=("just: https://just.systems/man/en/packages.html")
    fi

    if [ ${#missing_deps[@]} -gt 0 ]; then
        echo >&2 "Error: Missing required dependencies:"
        printf >&2 -- "- %s\n" "${missing_deps[@]}"
        echo >&2
        echo >&2 "Please install the missing dependencies and try again."
        exit 1
    fi
}

check_dependencies

"$ROOT_DIR/bash/create-symlink.sh"
"$ROOT_DIR/pick/update-justfile.sh" "$@"
"$ROOT_DIR/pick/pick.sh" true --write-on-cancel
just _just_bash_hint
