#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(dirname -- "${BASH_SOURCE[0]}")"

JUSTFILE=$(find "$PWD" -maxdepth 1 -type f -name "[Jj]ustfile" -o -name "\.[Jj]ustfile" | head -n1)

"$ROOT_DIR/pick/write-default-imports.sh" "$JUSTFILE"
